<?php

/*
|--------------------------------------------------------------------------
| ALT-152A (VirtualOpacity) state acceptance
|--------------------------------------------------------------------------
|
| Michael, 2026-09-27 -- carried over from the live vr-states.php as-is.
| Used by the ALT-152A State Status Map (/vr-states). Update a state here
| and redeploy (then `php artisan config:cache`, which caa-deploy runs).
|
| statuses: "State" or "XX - Regional agency" => Accepted | Accepted
|           Conditionally | Pending | Not Accepted. Regional entries are
|           grouped under their state by the two-letter prefix.
| letters:  acceptance-letter PDFs, relative to public/, per state code.
|           A link only shows once that file exists.
*/

return [

    'statuses' => [
        'Alabama' => 'Accepted',
        'Alaska' => 'Accepted',
        'Arizona' => 'Accepted',
        'Arkansas' => 'Accepted',
        'California' => 'Accepted',
        'CA - Amador County APCD' => 'Pending',
        'CA - Antelope Valley AQMD' => 'Pending',
        'CA - Bay Area AQMD' => 'Pending',
        'CA - Butte County AQMD' => 'Pending',
        'CA - Calaveras County APCD' => 'Pending',
        'CA - Colusa County APCD' => 'Pending',
        'CA - Eastern Kern APCD' => 'Pending',
        'CA - El Dorado County' => 'Pending',
        'CA - Feather River AQMD' => 'Pending',
        'CA - Glenn County APCD' => 'Pending',
        'CA - Great Basin Unified APCD' => 'Pending',
        'CA - Imperial County' => 'Pending',
        'CA - Lake County AQMD' => 'Pending',
        'CA - Lassen County APCD' => 'Pending',
        'CA - Mariposa County APCD' => 'Pending',
        'CA - Mendocino County AQMD' => 'Pending',
        'CA - Modoc County APCD' => 'Pending',
        'CA - Mojave Desert AQMD' => 'Accepted',
        'CA - Monterey Bay Air Resources District' => 'Pending',
        'CA - North Coast Unified AQMD' => 'Pending',
        'CA - Northern Sierra AQMD' => 'Pending',
        'CA - Northern Sonoma County APCD' => 'Pending',
        'CA - Placer County APCD' => 'Pending',
        'CA - Sacramento Metro AQMD' => 'Pending',
        'CA - San Diego County APCD' => 'Pending',
        'CA - San Joaquin Valley APCD' => 'Pending',
        'CA - San Luis Obispo County APCD' => 'Pending',
        'CA - Santa Barbara County APCD' => 'Pending',
        'CA - Shasta County AQMD' => 'Pending',
        'CA - Siskiyou County APCD' => 'Pending',
        'CA - South Coast AQMD' => 'Pending',
        'CA - Tehama County APCD' => 'Pending',
        'CA - Tuolumne County APCD' => 'Pending',
        'CA - Ventura County' => 'Pending',
        'CA - Yolo-Salono AQMD' => 'Pending',
        'Colorado' => 'Accepted',
        'Connecticut' => 'Pending',
        'Delaware' => 'Accepted Conditionally',
        'Florida' => 'Accepted',
        'Georgia' => 'Accepted',
        'Hawaii' => 'Accepted',
        'Idaho' => 'Accepted',
        'Illinois' => 'Pending',
        'Indiana' => 'Accepted',
        'Iowa' => 'Accepted',
        'Kansas' => 'Pending',
        'Kentucky' => 'Accepted',
        'Louisiana' => 'Accepted',
        'Maine' => 'Pending',
        'Maryland' => 'Accepted',
        'Massachusetts' => 'Pending',
        'Michigan' => 'Pending',
        'Minnesota' => 'Accepted',
        'Mississippi' => 'Accepted',
        'Missouri' => 'Pending',
        'Montana' => 'Accepted',
        'Nebraska' => 'Pending',
        'Nevada' => 'Pending',
        'New Hampshire' => 'Pending',
        'New Jersey' => 'Accepted',
        'New Mexico' => 'Accepted',
        'New York' => 'Accepted',
        'North Carolina' => 'Accepted',
        'North Dakota' => 'Pending',
        'Ohio' => 'Accepted',
        'Oklahoma' => 'Pending',
        'Oregon' => 'Accepted',
        'Pennsylvania' => 'Pending',
        'Rhode Island' => 'Accepted',
        'South Carolina' => 'Accepted',
        'South Dakota' => 'Not Accepted',
        'Tennessee' => 'Accepted',
        'Texas' => 'Accepted',
        'Utah' => 'Accepted',
        'Vermont' => 'Pending',
        'Virginia' => 'Accepted',
        'Washington' => 'Accepted',
        'West Virginia' => 'Accepted',
        'Wisconsin' => 'Pending',
        'Wyoming' => 'Accepted',
        'WY - Casper' => 'Pending',
        'WY - Cheyenne' => 'Pending',
        'WY - Lander' => 'Pending',
        'WY - Pinedale' => 'Pending',
        'WY - Sheridan' => 'Pending',
    ],

    // From the live sitemap (ALT-152A-Acceptance/...).
    'letters' => [
        'AL' => [['label' => 'Alabama acceptance letter', 'file' => 'ALT-152A-Acceptance/AL-State-Acceptance-Method-ALT-152A.pdf']],
        'AK' => [['label' => 'Alaska acceptance letter', 'file' => 'ALT-152A-Acceptance/AK-State-Acceptance-Method-ALT-152A.pdf']],
        'AZ' => [
            ['label' => 'Arizona acceptance letter', 'file' => 'ALT-152A-Acceptance/AZ-State-Acceptance-Method-ALT-152A.pdf'],
            ['label' => 'Maricopa County Air Quality acceptance letter', 'file' => 'ALT-152A-Acceptance/AZ-Maricopa-County-Air-State-Acceptance-Method-ALT-152A.pdf'],
        ],
        'AR' => [['label' => 'Arkansas acceptance letter', 'file' => 'ALT-152A-Acceptance/AR-State-Acceptance-Method-ALT-152A.pdf']],
        'CO' => [['label' => 'Colorado acceptance letter', 'file' => 'ALT-152A-Acceptance/CO-State-Acceptance-Method-ALT-152A.pdf']],
        'FL' => [['label' => 'Florida acceptance letter', 'file' => 'ALT-152A-Acceptance/FL-State-Acceptance-Method-ALT-152A.pdf']],
        'HI' => [['label' => 'Hawaii acceptance letter', 'file' => 'ALT-152A-Acceptance/HI-State-Acceptance-Method-ALT-152A.pdf']],
        'ID' => [['label' => 'Idaho acceptance letter', 'file' => 'ALT-152A-Acceptance/ID-State-Acceptance-Method-ALT-152A.pdf']],
        'IN' => [['label' => 'Indiana acceptance letter', 'file' => 'ALT-152A-Acceptance/IN-State-Acceptance-Method-ALT-152A.pdf']],
        'IA' => [['label' => 'Iowa acceptance letter', 'file' => 'ALT-152A-Acceptance/IA-State-Acceptance-Method-ALT-152A.pdf']],
        'KY' => [['label' => 'Kentucky acceptance letter', 'file' => 'ALT-152A-Acceptance/KY-State-Acceptance-Method-ALT-152A.pdf']],
        'LA' => [['label' => 'Louisiana acceptance letter', 'file' => 'ALT-152A-Acceptance/LA-State-Acceptance-Method-ALT-152A.pdf']],
        'MD' => [['label' => 'Maryland acceptance letter', 'file' => 'ALT-152A-Acceptance/MD-State-Acceptance-Method-ALT-152A.pdf']],
        'MI' => [['label' => 'Michigan acceptance letter', 'file' => 'ALT-152A-Acceptance/MI-State-Acceptance-Method-ALT-152A.pdf']],
        'MN' => [['label' => 'Minnesota acceptance letter', 'file' => 'ALT-152A-Acceptance/MN-State-Acceptance-Method-ALT-152A.pdf']],
        'MS' => [['label' => 'Mississippi acceptance letter', 'file' => 'ALT-152A-Acceptance/MS-State-Acceptance-Method-ALT-152A.pdf']],
        'MT' => [
            ['label' => 'Montana acceptance letter', 'file' => 'ALT-152A-Acceptance/MT-State-Acceptance-Method-ALT-152A.pdf'],
            ['label' => 'Montana email correspondence', 'file' => 'ALT-152A-Acceptance/MT-Email-Thread-State-Acceptance-Method-ALT-152A.pdf'],
        ],
        'NM' => [['label' => 'New Mexico acceptance letter', 'file' => 'ALT-152A-Acceptance/NM-State-Acceptance-Method-ALT-152A.pdf']],
        'NY' => [['label' => 'New York acceptance letter', 'file' => 'ALT-152A-Acceptance/NY-State-Acceptance-Method-ALT-152A.pdf']],
        'NC' => [['label' => 'North Carolina acceptance letter', 'file' => 'ALT-152A-Acceptance/NC-State-Acceptance-Method-ALT-152A.pdf']],
        'OH' => [['label' => 'Ohio acceptance letter', 'file' => 'ALT-152A-Acceptance/OH-State-Acceptance-Method-ALT-152A.pdf']],
        'OK' => [['label' => 'Oklahoma acceptance letter', 'file' => 'ALT-152A-Acceptance/OK-State-Acceptance-Method-ALT-152A.pdf']],
        'OR' => [['label' => 'Oregon acceptance letter', 'file' => 'ALT-152A-Acceptance/OR-State-Acceptance-Method-ALT-152A.pdf']],
        'RI' => [['label' => 'Rhode Island acceptance letter', 'file' => 'ALT-152A-Acceptance/RI-State-Acceptance-Method-ALT-152A.pdf']],
        'SD' => [['label' => 'South Dakota letter (not approved)', 'file' => 'ALT-152A-Acceptance/SD-NOT-APPROVED-State-Acceptance-Method-ALT-152A.pdf']],
        'TX' => [['label' => 'Texas acceptance letter', 'file' => 'ALT-152A-Acceptance/TX-State-Acceptance-Method-ALT-152A.pdf']],
        'UT' => [['label' => 'Utah acceptance letter', 'file' => 'ALT-152A-Acceptance/UT-State-Acceptance-Method-ALT-152A.pdf']],
        'WA' => [
            ['label' => 'Olympic Region Clean Air Agency (ORCAA) acceptance letter', 'file' => 'ALT-152A-Acceptance/WA-ORCAA-Olympia-Region-State-Acceptance-Method-ALT-152A.pdf'],
            ['label' => 'Puget Sound Clean Air Agency (Seattle) acceptance letter', 'file' => 'ALT-152A-Acceptance/WA-Seattle-Air-District-PSCAA-State-Acceptance-Method-ALT-152A.pdf'],
        ],
        'WV' => [['label' => 'West Virginia acceptance letter', 'file' => 'ALT-152A-Acceptance/WV-State-Acceptance-Method-ALT-152A.pdf']],
        'WI' => [['label' => 'Wisconsin acceptance letter', 'file' => 'ALT-152A-Acceptance/WI-State-Acceptance-Method-ALT-152A.pdf']],
        'WY' => [['label' => 'Wyoming acceptance letter', 'file' => 'ALT-152A-Acceptance/WY-State-Acceptance-Method-ALT-152A.pdf']],
    ],

];
