/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MailRouteImport } from './routes/mail'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as InquiriesIndexRouteImport } from './routes/inquiries.index'
import { Route as InquiriesInquiryIdRouteImport } from './routes/inquiries.$inquiryId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesIndexRoute = InquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesInquiryIdRoute = InquiriesInquiryIdRouteImport.update({
  id: '/inquiries/$inquiryId',
  path: '/inquiries/$inquiryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/inquiries/$inquiryId': typeof InquiriesInquiryIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/inquiries/': typeof InquiriesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/inquiries/$inquiryId': typeof InquiriesInquiryIdRoute
  '/clients': typeof ClientsIndexRoute
  '/inquiries': typeof InquiriesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/inquiries/$inquiryId': typeof InquiriesInquiryIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/inquiries/': typeof InquiriesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mail'
    | '/schools'
    | '/settings'
    | '/templates'
    | '/clients/$clientId'
    | '/inquiries/$inquiryId'
    | '/clients/'
    | '/inquiries/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mail'
    | '/schools'
    | '/settings'
    | '/templates'
    | '/clients/$clientId'
    | '/inquiries/$inquiryId'
    | '/clients'
    | '/inquiries'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/mail'
    | '/schools'
    | '/settings'
    | '/templates'
    | '/clients/$clientId'
    | '/inquiries/$inquiryId'
    | '/clients/'
    | '/inquiries/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MailRoute: typeof MailRoute
  SchoolsRoute: typeof SchoolsRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  InquiriesInquiryIdRoute: typeof InquiriesInquiryIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  InquiriesIndexRoute: typeof InquiriesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries/': {
      id: '/inquiries/'
      path: '/inquiries'
      fullPath: '/inquiries/'
      preLoaderRoute: typeof InquiriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries/$inquiryId': {
      id: '/inquiries/$inquiryId'
      path: '/inquiries/$inquiryId'
      fullPath: '/inquiries/$inquiryId'
      preLoaderRoute: typeof InquiriesInquiryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MailRoute: MailRoute,
  SchoolsRoute: SchoolsRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  InquiriesInquiryIdRoute: InquiriesInquiryIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  InquiriesIndexRoute: InquiriesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
