"""Generates resources/views/public/partials/us-states-map.blade.php from
states-albers-10m.json (us-atlas 3.0.1, ISC license -- see LICENSE here).

The source is TopoJSON already projected to Albers USA (Alaska/Hawaii
inset) in a 975x610 box, so no map projection is needed: this only decodes
the quantized, delta-encoded arcs back into SVG path strings, one <path>
per state tagged with its USPS code. Run from this folder:

    python generate-us-map.py
"""
import json
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE.parent / 'views' / 'public' / 'partials' / 'us-states-map.blade.php'

FIPS_TO_USPS = {
    '01': 'AL', '02': 'AK', '04': 'AZ', '05': 'AR', '06': 'CA', '08': 'CO', '09': 'CT',
    '10': 'DE', '11': 'DC', '12': 'FL', '13': 'GA', '15': 'HI', '16': 'ID', '17': 'IL',
    '18': 'IN', '19': 'IA', '20': 'KS', '21': 'KY', '22': 'LA', '23': 'ME', '24': 'MD',
    '25': 'MA', '26': 'MI', '27': 'MN', '28': 'MS', '29': 'MO', '30': 'MT', '31': 'NE',
    '32': 'NV', '33': 'NH', '34': 'NJ', '35': 'NM', '36': 'NY', '37': 'NC', '38': 'ND',
    '39': 'OH', '40': 'OK', '41': 'OR', '42': 'PA', '44': 'RI', '45': 'SC', '46': 'SD',
    '47': 'TN', '48': 'TX', '49': 'UT', '50': 'VT', '51': 'VA', '53': 'WA', '54': 'WV',
    '55': 'WI', '56': 'WY',
}


def decode_arcs(topology):
    scale = topology['transform']['scale']
    translate = topology['transform']['translate']
    arcs = []
    for arc in topology['arcs']:
        x = y = 0
        points = []
        for dx, dy in arc:
            x += dx
            y += dy
            points.append((x * scale[0] + translate[0], y * scale[1] + translate[1]))
        arcs.append(points)
    return arcs


def ring_points(ring, arcs):
    points = []
    for index in ring:
        arc = arcs[index] if index >= 0 else list(reversed(arcs[~index]))
        points.extend(arc if not points else arc[1:])
    return points


def geometry_path(geometry, arcs):
    polygons = geometry['arcs'] if geometry['type'] == 'MultiPolygon' else [geometry['arcs']]
    parts = []
    for polygon in polygons:
        for ring in polygon:
            pts = ring_points(ring, arcs)
            parts.append('M' + 'L'.join(f'{x:.1f},{y:.1f}' for x, y in pts) + 'Z')
    return ''.join(parts)


def main():
    topology = json.loads((HERE / 'states-albers-10m.json').read_text(encoding='utf-8'))
    arcs = decode_arcs(topology)
    states = sorted(topology['objects']['states']['geometries'], key=lambda g: g['properties']['name'])

    lines = [
        "{{-- GENERATED by resources/map-source/generate-us-map.py -- do not edit by hand.",
        "     State outlines from us-atlas 3.0.1 (US Census Bureau cartographic boundaries),",
        "     Copyright 2013-2019 Michael Bostock, ISC license: resources/map-source/LICENSE --}}",
        '<svg class="us-map" viewBox="0 0 975 610" role="group" aria-label="Map of the United States">',
    ]
    for g in states:
        code = FIPS_TO_USPS[g['id']]
        name = g['properties']['name']
        lines.append(
            f'  <path class="us-state" data-state="{code}" data-name="{name}" tabindex="0" role="button" '
            f'aria-label="{name}" d="{geometry_path(g, arcs)}"><title>{name}</title></path>'
        )
    lines.append('</svg>')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
    print(f'Wrote {len(states)} states to {OUT} ({OUT.stat().st_size // 1024} KB)')


if __name__ == '__main__':
    main()
